//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvtKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nvtKhoa()
        {
            this.nvtSVs = new HashSet<nvtSV>();
        }
    
        public string NvtID { get; set; }
        public string NvtTenKh { get; set; }
        public string NvtTrangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nvtSV> nvtSVs { get; set; }
    }
}
