//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvtSV
    {
        public string NvtMaSV { get; set; }
        public string NvtHoSV { get; set; }
        public string NvtTenSV { get; set; }
        public Nullable<System.DateTime> NvtNS { get; set; }
        public Nullable<bool> NvtPhai { get; set; }
        public string NvtPhone { get; set; }
        public string NvtEmail { get; set; }
        public string NvtID { get; set; }
    
        public virtual nvtKhoa nvtKhoa { get; set; }
    }
}
